### PR TITLE
Dual license under EPL2.0

### PR DESCRIPTION
**Pull request by mihnita**

### CODE REVIEW

**Comment by mihnita** [comment]
Hi all,

You've all contributed to this project (Ansi Escapes for Eclipse) at some point, not matter how little.

I've added you as collaborators so that you can review (and hopefully approve) a change in license.
From Apache 2 to dual license Apache License v2 + Eclipse Public License v2.0.
That is because there is some interest for this functionality (and code) to become part of Eclipse proper.

Thank you very much,
Mihai

**Comment by mihnita** [comment]
Note: I've modeled this after https://github.com/eclipse/jetty.project/issues/5784
Which also uses a dual license Apache 2 / Eclipse 2.

**Review by bendiscz — APPROVED** [review]

**Review by hititipi — APPROVED** [review]

**Review by martinlippert — APPROVED** [review]

**Comment by caco3** [comment]
My only contribution was to update the URL in the readme (https://github.com/mihnita/ansi-econsole/commit/de31fec20709eace31002cc12026940de7d64e8e). There is no need to mention me for this :)

**Review by caco3 — APPROVED** [review]

**Comment by caco3** [comment]
@mihnita And  thanks for your great work!

**Review by ryantenney — APPROVED** [review]

**Comment by mihnita** [comment]
Thank you all! Submitting.

**Pull request merged**
